name: Compress, Upload to S3, and Deploy CloudFormation Stack

on:
  push:
    branches:
      - main

jobs:
  package-upload-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Compress the Python script into a .zip file
      - name: Compress Lambda function
        run: |
          mkdir -p package
          cp src/lambda_function.py package/
          cd package
          zip -r ../lambda_function.zip .
          cd ..

      # Step 3: Upload the .zip file to an S3 bucket
      - name: Upload to S3
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload Lambda function to S3
        run: |
          aws s3 cp lambda_function.zip s3://$BUCKET_NAME/lambda_function.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}

      # Step 4: Deploy the CloudFormation stack
      - name: Deploy CloudFormation stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        env:
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        with:
          name: MyCloudFormationStack
          template: templates/cloudformation-template.yaml
          capabilities: CAPABILITY_NAMED_IAM
          parameter-overrides: |
            ParameterKey=LambdaRuntime,ParameterValue=python3.8
            ParameterKey=LambdaMemorySize,ParameterValue=128
            ParameterKey=CodeS3Bucket,ParameterValue=$BUCKET_NAME
            ParameterKey=CodeS3Key,ParameterValue=lambda_function.zip
